{
 "title": "Seed Client",
 "description": "Grafana dashboard for dragonfly seed client.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(dragonfly_client_version,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_client_version{container=\"seed-client\",namespace=~\"$namespace\"}) by (git_version, git_commit)",
     "legendFormat": "{{git_version}}-{{git_commit}}"
    }
   ]
  },
  {
   "title": "Download Traffic",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_client_download_traffic{container=\"seed-client\",namespace=~\"$namespace\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upload Traffic",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_client_upload_traffic{container=\"seed-client\",namespace=~\"$namespace\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Download Task",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_client_download_task_total{container=\"seed-client\",namespace=~\"$namespace\"}) by (tag, app, priority)",
     "legendFormat": "{{tag}}-{{app}}-{{priority}}"
    }
   ]
  },
  {
   "title": "Download Task Type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_client_download_task_total{container=\"seed-client\",namespace=~\"$namespace\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Prefetch Task",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_client_prefetch_task_total{container=\"seed-client\",namespace=~\"$namespace\"}) by (tag, app, priority)",
     "legendFormat": "{{tag}}-{{app}}-{{priority}}"
    }
   ]
  },
  {
   "title": "Download Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_client_download_traffic{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]) * 8) by (type) or vector(0)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upload Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_client_upload_traffic{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]) * 8) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Download Hit Local Peer Traffic(Instance)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_client_download_traffic{type=\"LOCAL_PEER\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]) * 8) by (instance, container) or vector(0)",
     "legendFormat": "{{instance}}-{{container}}"
    }
   ]
  },
  {
   "title": "Download Hit Remote Peer Traffic(Instance)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_client_download_traffic{type=\"REMOTE_PEER\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]) * 8) by (instance, container) or vector(0)",
     "legendFormat": "{{instance}}-{{container}}"
    }
   ]
  },
  {
   "title": "Download Back To Source Traffic(Instance)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_client_download_traffic{type=\"BACK_TO_SOURCE\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]) * 8) by (instance, container) or vector(0)",
     "legendFormat": "{{instance}}-{{container}}"
    }
   ]
  },
  {
   "title": "Upload Traffic(Instance)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_client_upload_traffic{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]) * 8) by (instance, container) or vector(0)",
     "legendFormat": "{{instance}}-{{container}}"
    }
   ]
  },
  {
   "title": "Concurrent Download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(dragonfly_client_concurrent_download_task_total{container=\"seed-client\",namespace=~\"$namespace\"}) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Proxy Request Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_client_proxy_request_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_client_proxy_request_failure_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(dragonfly_client_proxy_request_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Request QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_client_proxy_request_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_client_proxy_request_total{container=\"seed-client\", namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Proxy Request(instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(dragonfly_client_proxy_request_total{container=\"seed-client\", namespace=~\"$namespace\"}[$__rate_interval]) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Proxy Request Failed(instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(dragonfly_client_proxy_request_failure_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backend Request Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_client_backend_request_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_client_backend_request_failure_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(dragonfly_client_backend_request_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Request QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_client_backend_request_duration_milliseconds_count{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      dragonfly_client_backend_request_duration_milliseconds_bucket{\n       namespace=~\"$namespace\",container=\"seed-client\",\n      }[$__rate_interval]\n    )\n  ) \n)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      dragonfly_client_backend_request_duration_milliseconds_bucket{\n       namespace=~\"$namespace\",container=\"seed-client\",\n      }[$__rate_interval]\n    )\n  ) \n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      dragonfly_client_backend_request_duration_milliseconds_bucket{\n       namespace=~\"$namespace\",container=\"seed-client\",\n      }[$__rate_interval]\n    )\n  ) \n)",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Download Task Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_client_download_task_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_client_download_task_failure_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(dragonfly_client_download_task_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)"
    }
   ]
  },
  {
   "title": "Download Task QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_client_download_task_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Download Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(dragonfly_client_download_task_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]) or vector(0)",
     "legendFormat": "{{instance}}-{{container}}"
    }
   ]
  },
  {
   "title": "Download Task Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(dragonfly_client_download_task_failure_total{container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval]) or vector(0)",
     "legendFormat": "{{instance}}-{{container}}"
    }
   ]
  },
  { "title": "Task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Download Duration(0-1MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"1\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"1\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"1\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(1MB-4MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"2\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"2\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"2\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(4MB-8MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"3\",container=\"seed-client\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"3\",container=\"seed-client\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"3\",container=\"seed-client\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(8MB-16MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"4\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"4\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"4\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(16MB-32MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"5\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"5\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"5\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(32MB-64MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"6\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"6\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"6\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(64MB-128MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"7\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"7\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"7\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(128MB-256MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"8\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"8\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"8\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(256MB-512MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"9\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"9\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"9\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(512MB-1GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"10\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"10\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"10\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(1GB-4GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"11\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"11\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"11\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(4GB-8GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"12\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"12\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"12\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(8GB-16GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"13\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"13\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"13\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(16GB-32GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"14\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"14\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"14\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(32GB-64GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"15\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"15\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"15\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(64GB-128GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"16\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"16\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"16\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(128GB-256GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"17\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"17\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"17\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(256GB-512GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"18\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"18\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"18\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(512GB-1TB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"19\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"19\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"19\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Download Duration(1TB+)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"20\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"20\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dragonfly_client_download_task_duration_milliseconds_bucket{task_size_level=\"20\",container=\"seed-client\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)) or vector(0)",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 } },
  {
   "title": "Disk Usage Space Total",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_client_disk_usage_space_total{container=\"seed-client\",namespace=~\"$namespace\"})",
     "legendFormat": "Usage Space"
    },
    {
     "expr": "sum(dragonfly_client_disk_space_total{container=\"seed-client\",namespace=~\"$namespace\"}-\ndragonfly_client_disk_usage_space_total{container=\"seed-client\",namespace=~\"$namespace\"})",
     "legendFormat": "Free Space"
    }
   ]
  },
  {
   "title": "Disk Usage Space(Instance)",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dragonfly_client_disk_space_total{container=\"seed-client\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "dragonfly_client_disk_usage_space_total{container=\"seed-client\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "dragonfly_client_disk_space_total{container=\"seed-client\",namespace=~\"$namespace\"} - dragonfly_client_disk_usage_space_total{container=\"seed-client\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "dragonfly_client_disk_usage_space_total{container=\"seed-client\",namespace=~\"$namespace\"} /\ndragonfly_client_disk_space_total{container=\"seed-client\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 } },
  {
   "title": "Host Download Traffic Top 10",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(dragonfly_client_download_traffic{container=\"seed-client\",namespace=~\"$namespace\"}[1d])) by (instance, container))",
     "legendFormat": "{{instance}}-{{container}}"
    }
   ]
  },
  {
   "title": "Host Upload Traffic Top 10",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(dragonfly_client_upload_traffic{container=\"seed-client\",namespace=~\"$namespace\"}[1d])) by (instance, container))",
     "legendFormat": "{{instance}}-{{container}}"
    }
   ]
  },
  { "title": "Rust", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 193 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{container='seed-client',namespace=~\"$namespace\"}[1m])) by (instance, container)",
     "legendFormat": "{{instance}}-{{container}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{container=\"seed-client\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-{{container}}-resident"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_threads{container=\"seed-client\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-{{container}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{container=\"seed-client\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-{{container}}"
    }
   ]
  }
 ]
}