{
 "title": "Seed Peer",
 "description": "Granafa dashboard for dragonfly seed peer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Back Source Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dragonfly_dfdaemon_seed_peer_download_traffic{type=\"back_to_source\"}[1d]))"
    }
   ]
  },
  {
   "title": "Download Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(dragonfly_dfdaemon_seed_peer_download_total{}[$interval])) -\nsum(rate(dragonfly_dfdaemon_seed_peer_download_failure_total{}[$interval])))\n/ \nsum(rate(dragonfly_dfdaemon_seed_peer_download_total{}[$interval]))"
    }
   ]
  },
  {
   "title": "Download QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_dfdaemon_seed_peer_download_total{}[$interval]))"
    }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(dragonfly_dfdaemon_seed_peer_download_total{}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Download Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(dragonfly_dfdaemon_seed_peer_download_failure_total{}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Concurrent Downloading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dragonfly_dfdaemon_seed_peer_concurrent_download_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "GRPC Global Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handled_total{grpc_service=\"cdnsystem.Seeder\",grpc_type=\"unary\",grpc_code=\"OK\"}[$interval])) + \nsum(rate(grpc_server_handled_total{grpc_service=\"cdnsystem.Seeder\",grpc_type=\"unary\",grpc_code=\"NotFound\"}[$interval])) + \nsum(rate(grpc_server_handled_total{grpc_service=\"cdnsystem.Seeder\",grpc_type=\"unary\",grpc_code=\"PermissionDenied\"}[$interval])) + \nsum(rate(grpc_server_handled_total{grpc_service=\"cdnsystem.Seeder\",grpc_type=\"unary\",grpc_code=\"InvalidArgument\"}[$interval])))\n/ \nsum(rate(grpc_server_started_total{grpc_service=\"cdnsystem.Seeder\",grpc_type=\"unary\"}[$interval]))"
    }
   ]
  },
  {
   "title": "GRPC QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{grpc_service=\"cdnsystem.Seeder\"}[$interval]))"
    }
   ]
  },
  {
   "title": "GRPC request code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{grpc_service=\"cdnsystem.Seeder\",grpc_type=\"unary\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_method}}/{{grpc_code}}"
    }
   ]
  },
  { "title": "Golang", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{container=\"seed-peer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{container=\"seed-peer\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{}",
     "legendFormat": "{{instance}}-resident"
    },
    {
     "expr": "process_virtual_memory_bytes{container=\"seed-peer\"}",
     "legendFormat": "{{instance}}-virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{container=\"seed-peer\"}",
     "legendFormat": "{{instance}}-bytes_allocated"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{component=\"seed-peer\"}",
     "legendFormat": "{{instance}}-stack_inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{container=\"seed-peer\"}",
     "legendFormat": "{{instance}}-heap_inuse"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{container=\"seed-peer\"}[30s])",
     "legendFormat": "{{instance}}-alloc_rate"
    }
   ]
  }
 ]
}